name: Eelco Anneveldt - Creative
favicon: null
layout_spectrum: 0.0937
typography_spectrum: 0.5151795372366905
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030b0e'
    - '#425f6d'
    - '#00929d'
    - '#cde2e3'
    - '#af6d2c'
  brandStrength: 0.6135741998441517
  lightness: 0.8298713632393628
  saturation: 0.6257726906333119
  rhythmicContrast: 0.7341067008674145
purpose: []
